feat(mission-observation) : 178 mission   ajout observations gnrale de la mission
MTES-MCT/rapportnav2 pull request #196
Opened 2024-06-20 16:49 UTC by xtiannyeto

2024-07-01 13:50 UTC, lwih requested changes

2024-07-01 13:50 UTC, lwih commented on backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/env/MissionEnvEntity.kt
> +}
J'ai des doutes par rapport à cette classe artificielle, j'aurais plutot essayé de continuer avec le MissionEntity provenant de Env directement.
Tu appelles l'endpoint avec cette fonction: `fun updateMission(missionId: Int, mission: MissionEnvEntity): MissionEntity?` mais at some point, tu devras matcher avec [cet adapter](https://github.com/MTES-MCT/monitorenv/blob/main/backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/CreateOrUpdateMissionDataInput.kt) provenant de MonitorEnv et qui a des champs obligatoires.

donc dans tous les cas, il faudra reconstruire un objet CreateOrUpdateMissionDataInput assez proche du MissionEntity.
Regarde le commentaire que j'ai laissé dans ma PR et dis moi ce que t'en penses: https://github.com/MTES-MCT/rapportnav2/pull/173/files#diff-effb1b348d87dcfc07f59e73e5b93f0fc1f1b57e5396d7990391fc5415446c3d

2024-07-02 13:01 UTC, xtiannyeto commented on backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/config/HttpClientFactory.kt
> +}
Juste pour avoir la main sur le httpClient qu'on crée, plus facile a tester

2024-07-02 13:34 UTC, xtiannyeto commented on backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/monitorenv/APIEnvMissionRepository.kt
> +    }
yes +1

2024-07-02 13:35 UTC, xtiannyeto commented on frontend/src/pam/mission/use-update-mission-env.tsx
> +  })
ok. ca marche

2024-07-02 13:38 UTC, xtiannyeto commented on backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/env/MissionEnvEntity.kt
> +}
En fait on s'est mis d'accord avec Maxime, en entrée du patch on ne prend pas toute la missionEntity, juste quelque attributs. pour le moment uniquement `observationsByUnit`. je peux renommer le classe `UpdateMissionEnvEntity` pour que se soit plus claire. t'en penses quoi?

2024-07-02 15:29 UTC, lwih commented on backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/env/MissionEnvEntity.kt
> +}
Ah trop bien que vous vous soyez mis d'accord là dessus, c'est même mieux. Je vais updater ma branche en conséquence du coup.
Pas contre renommer en `PatchMissionEnvEntity` mais optionel. Je valide la PR dans tous les cas.

2024-07-02 15:32 UTC, lwih approved these changes
Bien joué.
Je vais pouvoir réutiliser ton code en plus.
Tu peux merger quand tu veux vu que le textarea est caché pour l'instant

2024-07-08 11:17 UTC, merged